import type { AnalysisResult, UploadedImage } from '../types'

export function downloadReport(
  images: UploadedImage[],
  question: string,
  result: AnalysisResult,
): void {
  const lines: string[] = []
  lines.push('SatQuery AI - Analysis Report')
  lines.push('='.repeat(40))
  lines.push('')
  lines.push(`Input: ${images.map((i) => i.name).join(', ')}`)
  lines.push(`Location: ${images[0]?.location ?? 'n/a'}`)
  lines.push('')
  lines.push(`Question: ${question}`)
  lines.push('')
  lines.push(`Answer:`)
  lines.push(result.answer)
  lines.push('')
  lines.push(`Confidence: ${(result.confidence * 100).toFixed(0)}%`)
  lines.push(`Workflow: ${result.workflowLabel}`)
  lines.push(`Models: ${result.modelNames.join(', ')}`)
  lines.push(`Processing time: ${result.usageTimeSec.toFixed(1)}s`)
  lines.push('')
  lines.push('Generated by SatQuery AI (MVP demo prototype).')

  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `satquery-report-${Date.now()}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}